### ISSUE TITLE
Don‘t work with HA 2021.3.0b0

### ISSUE THREAD

**Issue by Krocko** [e2m32/hass_custom_timer#5]
Can you please have a look what has changed in the timer component in ha 2021.3.0b0?

Thank you very much.

**Comment by e2m32** [comment]
I can, thanks for the heads up. It may be a week or so. I will probably miss the 2021.3.0 release...

**Comment by e2m32** [comment]
At first glance it doesn't look like anything is going to break for this custom timer, but I will merge it in just to keep it current.

**Comment by robbinonline** [comment]
Unfortunately ut stops working in 2021.3.1

**Comment by databoy2k** [comment]
Also takes down default_config because it depends on timer.

Log Details on Error (HA 2021.3.1):

Logger: homeassistant.setup
Source: custom_components/timer/__init__.py:127
First occurred: 4:50:33 PM (1 occurrences)
Last logged: 4:50:33 PM

Error during setup of component timer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/timer/__init__.py", line 127, in async_setup
    collection.attach_entity_component_collection(
AttributeError: module 'homeassistant.helpers.collection' has no attribute 'attach_entity_component_collection'

**Comment by e2m32** [comment]
Ok, looks like we are back in business. Thank you everyone for the feedback. Please test and let me know if you run into any issues.

**Comment by Krocko** [comment]
@e2m32 With the new update I get the following error:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/timer/__init__.py:83 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 10:48:07 (6 occurrences) 
Last logged: 10:51:01

[140349275406928] 'str' object has no attribute 'total_seconds'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 712, in admin_handler
    await result
  File "/config/custom_components/timer/__init__.py", line 158, in reload_service_handler
    await yaml_collection.async_load(
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 164, in async_load
    await self.notify_changes(change_sets)
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 125, in notify_changes
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 333, in _collection_changed
    await entities[item_id].async_update_config(config)  # type: ignore
  File "/config/custom_components/timer/__init__.py", line 455, in async_update_config
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/config/custom_components/timer/__init__.py", line 277, in state_attributes
    ATTR_RESTORE_GRACE_PERIOD: _format_timedelta(self._restore_grace_period),
  File "/config/custom_components/timer/__init__.py", line 83, in _format_timedelta
    total_seconds = delta.total_seconds()
AttributeError: 'str' object has no attribute 'total_seconds'
```

**Comment by e2m32** [comment]
@Krocko can you share what your `restore_grace_period`s look like in your config? I need something to test with to try and recreate this error.

**Comment by Krocko** [comment]
@e2m32 The error only occurs if I reload the timer in the frontend.
```
timer:
  zahnburste_ladetimer:
    name: Zahnbürste  Ladetimer
    duration: '30:00:00'
    icon: mdi:timer-sand
    restore: true
    restore_grace_period: '00:15:00'
  ventilator_timer:
    name: Ventilator Timer
    icon: mdi:camera-timer
    restore: true
    restore_grace_period: '00:15:00'
```

**Comment by e2m32** [comment]
@Krocko 💡 I completely forgot about that button for testing. Ok, I have fixed the error... but I still need to work on preventing all your timers from being reset to idle after you press that button. stand by.

**Comment by antonbalaban** [comment]
EDIT: Sorry, please ignore my post. Instead of deleting old /timer folder i renamed it "timer_old" and copied a new version alongside. Home assistant somehow used files from "timer_old" and component failed. After I deleted it all went to normal.

Having the same problem on HA 2021.3.3

```
Logger: homeassistant.setup
Source: custom_components/timer_old/__init__.py:127 
First occurred: 6:14:12 PM (1 occurrences) 
Last logged: 6:14:12 PM

Error during setup of component timer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/timer_old/__init__.py", line 127, in async_setup
    collection.attach_entity_component_collection(
AttributeError: module 'homeassistant.helpers.collection' has no attribute `'attach_entity_component_collection
```
My configuration:

```
timer:
  dryer:
    duration: '23:59:00'
    restore: true
    restore_grace_period: '00:15:00'
  soldering:
    duration: '00:35:00'
    restore: true
    restore_grace_period: '00:15:00'
```

**Comment by Krocko** [comment]
@e2m32 Please see my fork. This is working for me.

**Comment by e2m32** [comment]
@Krocko check the new release: [2021.3.2_1](https://github.com/e2m32/hass_custom_timer/releases/tag/2021.3.2_1). I looked at your code. I think it resolves the error message, but I'm pretty sure you're just removing the button functionality. Unless the core code is redundant.
